DylanDevelops/aidentify

- components/navbar.tsx
This pull request includes a small change to the `components/navbar.tsx` file. The change aligns the `ProfileMenubarContent` to the end.
* [`components/navbar.tsx`](diffhunk://#diff-697415f51799297bd64388e550f60789de985cb60aca6be2175bc512c9243626L74-R74): Modified the `ProfileMenubarContent` component to include an `align="end"` attribute.
> Made logout dropdown align on the right side of navbar

- app/(gameplay)/game/_context/GameContext.tsx
This pull request includes a small but significant change to the `GameContext.tsx` file. The number of levels pulled per game has been increased from 2 to 5 to account for new levels being added to the backend db.
* [`app/(gameplay)/game/_context/GameContext.tsx`](diffhunk://#diff-599aee49dfdc96c778457c7ef11ecf6ee1cfb73f3fa625b49aef22023193398dL63-R63): Updated the `numOfLevels` parameter in the `useQuery` call for `getRandomLevels` to 5.
> [Improvement] Changed Levels Per Game from 2 to 5

- components/footer.tsx
- components/version-button.tsx
This pull request refactors the `Footer` component to improve maintainability and user experience by creating a new `VersionButton` component that dynamically fetches the latest release version from GitHub. The most important changes include the removal of the static version import, the addition of the `VersionButton` component, and the dynamic fetching of the version.
This removes the need to manually set the version number everytime that we have a release.
Refactoring and improvements:
* [`components/footer.tsx`](diffhunk://#diff-bd3f659ee78d8c923c9975bdb8842b2a346ff04023e42fe215c0d080ef5cf115L4-L9): Removed the static import of the version from `package.json` and replaced the version display with the new `VersionButton` component. …
> [Improvement] Version Number Shown in Footer Now Gets Dynamically Pulled From GitHub

- components/footer.tsx
This pull request includes a small change to the `components/footer.tsx` file. The change updates the copyright year.
* [`components/footer.tsx`](diffhunk://#diff-bd3f659ee78d8c923c9975bdb8842b2a346ff04023e42fe215c0d080ef5cf115L13-R13): Updated the copyright year from 2024 to 2025.
We don't want to merge this until the new year. I just set up this PR to be ready to go.
> [fix] Updated Footer Year from 2024 to 2025

- convex/_generated/api.d.ts
- convex/_generated/api.js
- convex/_generated/dataModel.d.ts
- convex/_generated/server.d.ts
- convex/_generated/server.js
- package-lock.json
- package.json
This pull request includes several updates and cleanups to the `convex` related files and dependencies. The main changes involve removing `prettier-ignore` comments and updating the `convex` package version in `package.json`.
Code cleanup:
* [`convex/_generated/api.js`](diffhunk://#diff-89f91cbbe173e8910af00b1f744d913650a31629b66b5ff19fc553df4253fa39L1-L2): Removed `prettier-ignore` comments to allow Prettier to format the code. [[1]](diffhunk://#diff-89f91cbbe173e8910af00b1f744d913650a31629b66b5ff19fc553df4253fa39L1-L2) [[2]](diffhunk://#diff-89f91cbbe173e8910af00b1f744d913650a31629b66b5ff19fc553df4253fa39L25-L26)
* [`convex/_generated/server.js`](diffhunk://#diff-e1349194c8374e2307d5e2a2f66f4e8ec51cf50d67f61db0bc5e7620eec600f4L1-L2): Removed `prettier-ignore` comments to allow Prettier …
> [dependency] Bump convex version to `1.21.0`

- app/(gameplay)/game/_context/GameContext.tsx
- convex/auth.config.ts
- convex/game.ts
- convex/schema.ts
- convex/users.ts
This pull request introduces several changes to the `GameContext` and related files to enhance user handling and game functionality. The most significant changes include integrating Clerk for user management, adding a mutation to finish the game, and updating the schema to use `points` instead of `currentXP`.
* [`app/(gameplay)/game/_context/GameContext.tsx`](diffhunk://#diff-599aee49dfdc96c778457c7ef11ecf6ee1cfb73f3fa625b49aef22023193398dR3): Integrated Clerk for user management by importing `useUser` and fetching the user data using `useQuery`. [[1]](diffhunk://#diff-599aee49dfdc96c778457c7ef11ecf6ee1cfb73f3fa625b49aef22023193398dR3) [[2]](diffhunk://#diff-599aee49dfdc96c778457c7ef11ecf6ee1cfb73f3fa625b49aef22023193398dR42-R44)
* …
> [added] Points System

- app/(gameplay)/game/_components/ImageGame.tsx
- app/(marketing)/_components/heading.tsx
This pull request includes several changes to the `ImageGame` and `Heading` components to improve the layout and styling for better user experience. The most important changes include modifications to the image dimensions, text alignment, and styling adjustments.
* [`app/(gameplay)/game/_components/ImageGame.tsx`](diffhunk://#diff-d264f32dfcd3a43a616e364337fac1c665ae2ef32454c174d3aba5c5eb3dcd55L41-R42): Changed the image dimensions from fixed `25rem` to responsive sizes (`20rem` for smaller screens and `25rem` for larger screens) to improve the layout on different devices. [[1]](diffhunk://#diff-d264f32dfcd3a43a616e364337fac1c665ae2ef32454c174d3aba5c5eb3dcd55L41-R42) [[2]](diffhunk://#diff-d264f32dfcd3a43a616e364337fac1c665ae2ef32454c174d3aba5c5eb3dcd55L52-R55) …
> [fix] Mobile Formatting Improvements

- components/navbar.tsx
This pull request includes a significant change to the `Navbar` component in `components/navbar.tsx`. The main change involves replacing the `useScrollTop` hook with a custom scroll event listener to manage the `scrolled` state.
Changes to `Navbar` component:
* [`components/navbar.tsx`](diffhunk://#diff-697415f51799297bd64388e550f60789de985cb60aca6be2175bc512c9243626L21-R36): Replaced the `useScrollTop` hook with a custom scroll event listener using `useState` and `useEffect` to manage the `scrolled` state. This change ensures that the `scrolled` state is updated based on the window's scroll position.
Before (when loading page when already scrolled):
After:
> [fix] Navbar blur lag

- convex/levelUpload.ts
This pull request includes an improvement to the `createLevelWithImageIds` mutation in the `convex/levelUpload.ts` file. The change ensures that any empty hints are filtered out before being inserted into the database.
* [`convex/levelUpload.ts`](diffhunk://#diff-10bb17b00f17f544c308009d229f2a6acbc0e4646678cc83b8d1c2ff181b44b1R66-R71): Added a filter to remove empty hints from the `args.hints` array before inserting the level data into the database.
> [fix] Empty hints are now filtered out

- app/(authentication)/layout.tsx
- app/(developer)/layout.tsx
- app/(gameplay)/layout.tsx
- app/(legal)/layout.tsx
- app/(main)/layout.tsx
- app/(marketing)/layout.tsx
- components/navbar/navbar.css
- components/navbar/navbar.tsx
This pull request includes several changes to the import paths for the `Navbar` component across different layout files, as well as some modifications to the `navbar` component itself. The most important changes are summarized below:
* [`app/(authentication)/layout.tsx`](diffhunk://#diff-1deb75ce6b6c78367f1de1022c7750dd34c2124068bd3b55e075241031324fd9L2-R2): Updated the import path for `Navbar` to `@/components/navbar/navbar`.
* [`app/(developer)/layout.tsx`](diffhunk://#diff-abd703306a6ba1f11c736b320988cd1b12e1ca4a87bce0b6d3e3e749bd23501cL4-R4): Updated the import path for `Navbar` to `@/components/navbar/navbar`.
* [`app/(gameplay)/layout.tsx`](diffhunk://#diff-8da13aadb12a3c3a096af96415ef619975e118200a80c09606565951f3b9a6baL2-R2): Updated the import path for `Navbar` to …
> [fix] Removed redundant save and cancel buttons on user settings profile modal

- app/(main)/about/page.tsx
This pull request includes a small change to the `app/(main)/about/page.tsx` file. The change updates the titles of team members to reflect their leadership roles.
* Updated `Dylan Ravel`'s title to "Development Lead" (`app/(main)/about/page.tsx`)
* Updated `Divi Newton`'s title to "Design Lead" (`app/(main)/about/page.tsx`)
* Updated `Noslen Cruz-Muniz`'s title to "Curriculum Lead" and removed the `noPfp` attribute (`app/(main)/about/page.tsx`)
> [added] Noslen on team page + role updates

- app/(developer)/admin/_components/_level-upload/level-upload.tsx
This pull request includes a change to the `level-upload.tsx` file to enhance the validation logic for the level upload form. The main change is the addition of checks for level hints to ensure that at least one hint is provided before enabling the submit button.
Validation logic enhancement:
* [`app/(developer)/admin/_components/_level-upload/level-upload.tsx`](diffhunk://#diff-aa228d5cbc2858f3a11c6a75f9c89be33ec900709fd5ceb89e92c5f27db09da2L41-R46): Modified the `useEffect` dependency array and the validation condition to include `levelHint1`, `levelHint2`, and `levelHint3`, ensuring that the submit button is only enabled if at least one hint is provided.
> [fix] Require at least one hint when uploading a level

- app/(gameplay)/game/_components/ImageGame.tsx
This pull request includes changes to the `ImageGame` component in the `app/(gameplay)/game/_components/ImageGame.tsx` file. The most important changes focus on improving the layout and styling of the component.
Improvements to layout and styling:
* Removed a TODO comment and adjusted the padding for the inner `div` element to ensure proper spacing and alignment.
* Updated the `div` elements to use `max-h-full` instead of fixed height values, allowing for better responsiveness and overflow handling.
* Separated the `generationPrompt` into multiple lines for better readability and maintainability.
Before:
After:
> [fix] Big prompt cut off on in between rounds screen

- app/(gameplay)/game/_context/GameContext.tsx
- convex/_generated/api.d.ts
- convex/crons.ts
- convex/schema.ts
- convex/users.ts
This pull request introduces several changes to the game context and user management systems, focusing on updating user streaks and handling inactive users. The most important changes include adding a mutation to update user streaks, creating a cron job to reset inactive streaks, and modifying the schema for user data.
* Added `updateStreak` mutation to the `GameProvider` to update user streaks after each round. [[1]](diffhunk://#diff-599aee49dfdc96c778457c7ef11ecf6ee1cfb73f3fa625b49aef22023193398dR45) [[2]](diffhunk://#diff-599aee49dfdc96c778457c7ef11ecf6ee1cfb73f3fa625b49aef22023193398dR144-R147)
* Added a daily cron job to reset inactive user streaks.
* Modified the schema to replace `lastParticipationDate` with `lastPlayedTimestamp` for better timestamp handling.
* Replaced the …
> [added] Streak System

- app/(main)/leaderboard/page.tsx
- convex/users.ts
This pull request includes updates to the leaderboard page to display user streaks alongside their scores. The changes involve both the frontend and backend to support this new feature.
Frontend changes:
* [`app/(main)/leaderboard/page.tsx`](diffhunk://#diff-19760ee0d7b0700e4082e46fb0dfb70b8580c7d0070ab9b6b3193838abf94562L6-R6): Imported the `Flame` icon from `lucide-react` and added it to the leaderboard display to show user streaks. Updated the layout to accommodate the new streak information. [[1]](diffhunk://#diff-19760ee0d7b0700e4082e46fb0dfb70b8580c7d0070ab9b6b3193838abf94562L6-R6) [[2]](diffhunk://#diff-19760ee0d7b0700e4082e46fb0dfb70b8580c7d0070ab9b6b3193838abf94562L72-R81) [[3]](diffhunk://#diff-19760ee0d7b0700e4082e46fb0dfb70b8580c7d0070ab9b6b3193838abf94562L86-R101) …
> [added] Streaks on leaderboard entries on /leaderboard

- components/navbar/navbar.css
- components/navbar/navbar.tsx
This pull request introduces a new animation effect for the user streak count in the navbar component. The key changes include adding CSS for the animation, updating the `navbar.tsx` file to manage the animation state, and ensuring the streak count animates correctly when it changes.
Animation and styling updates:
* [`components/navbar/navbar.css`](diffhunk://#diff-94b89bb3b56dce9675f708d28e7bf5846437582ecd196c593c352082b1b3f303R5-R20): Added a new CSS class `.streak-tick` for the streak animation and defined the `tick-up` keyframes for the animation.
State management for animation:
* [`components/navbar/navbar.tsx`](diffhunk://#diff-6401eaec6ba32926e78bdb4fb50d10a41c75c9efb2a09f294c1eb7fb2617b784L9-R9): Imported `useRef` to manage the previous streak value and added state variables and …
> [added] Tick effect when streak increases

- convex/schema.ts
- convex/users.ts
This pull request introduces changes to the `convex` module to add and utilize a new `lastPlayTimestamp` field in the user schema, which helps in tracking the last time a user played. The most important changes include modifications to the schema definition and updates to the `finishDailyChallenge` and `updateStreak` mutations to use this new field.
Schema updates:
* [`convex/schema.ts`](diffhunk://#diff-00e6e27e65e72a0fd4a73f6942f41e1cf3f476a59f263513f3f47fdf801a0eb1R14): Added `lastPlayTimestamp` as an optional number field in the user schema.
Mutation updates:
* [`convex/users.ts`](diffhunk://#diff-26d9bc05df20f463382c8b6b0a926def0dd42b6c84ec6dffcbf721429b090847R127-R130): Updated the `finishDailyChallenge` mutation to set `lastPlayTimestamp` to the current time when a daily challenge …
> [fix] Streak and Daily challenge not updating correctly

- components/navbar/navbar.tsx
- hooks/use-daily-challenge-check.tsx
This pull request introduces a new utility function to check if a user can increase their daily challenge streak and integrates this function into the `Navbar` component. The most important changes include adding the new function, modifying the `Navbar` component to use this function, and updating the imports accordingly.
* [`hooks/use-daily-challenge-check.tsx`](diffhunk://#diff-750ccba48a826732caae779f13b97d687f7978385dcce99e831c6373927909c5R30-R63): Added the `canUserIncreaseStreak` function to determine if a user can increase their streak based on the last time they played the daily challenge.
* [`components/navbar/navbar.tsx`](diffhunk://#diff-6401eaec6ba32926e78bdb4fb50d10a41c75c9efb2a09f294c1eb7fb2617b784R20): Imported the `canUserIncreaseStreak` function.
* …
> [added] Visual indicator for when you are able to increase your streak

- package-lock.json
- package.json
This pull request includes an update to the `package.json` file to upgrade the `convex` package version.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L29-R29): Updated the `convex` package from version `1.22.0` to `1.23.0`.
> [dependency] Bump `convex` to `v1.23.0`

- convex/users.ts
This pull request includes a change to the `convex/users.ts` file to update the timestamp format for user participation.
Timestamp format update:
* [`convex/users.ts`](diffhunk://#diff-26d9bc05df20f463382c8b6b0a926def0dd42b6c84ec6dffcbf721429b090847L54-R54): Modified the `lastParticipationDate` field to use `Date.now()` instead of `new Date().toISOString()` for the `lastPlayTimestamp` field.
> [fix] New users unable to access account

- app/(gameplay)/results/page.tsx
- app/(main)/play/page.tsx
This pull request includes updates to the `GameResultPage` and `PlayPage` components to handle the introduction of a new game mode and improve user interface feedback.
Changes related to game mode handling and UI updates:
* [`app/(gameplay)/results/page.tsx`](diffhunk://#diff-65bb46b12ada4673b5194840e161cad63f0588420f3d0ffe40cfbac191e5cb42R105): Added a conditional check to exclude certain UI elements when the game mode is not "images" or "daily_challenge". This is a temporary change until the text mode is introduced. [[1]](diffhunk://#diff-65bb46b12ada4673b5194840e161cad63f0588420f3d0ffe40cfbac191e5cb42R105) [[2]](diffhunk://#diff-65bb46b12ada4673b5194840e161cad63f0588420f3d0ffe40cfbac191e5cb42R127)
* [`app/(main)/play/page.tsx`](diffhunk://#diff-986ac351d0af1ad2470f24cf6bee69b2d2b0b2bb75 …
> [removed] Play buttons are no longer clickable and show a coming soon message

- app/(main)/leaderboard/_components/desktop-leaderboard.tsx
- app/(main)/leaderboard/_components/leaderboard-helpers.ts
- app/(main)/leaderboard/_components/mobile-leaderboard-podium.tsx
- app/(main)/leaderboard/_components/mobile-leaderboard.tsx
- app/(main)/leaderboard/page.tsx
This pull request introduces significant updates to the leaderboard component, including the addition of separate desktop and mobile views, and refactoring of existing code for improved modularity and maintainability. The most important changes include the creation of new components for the leaderboard views, the addition of helper functions, and the removal of redundant code.
* [`app/(main)/leaderboard/_components/desktop-leaderboard.tsx`](diffhunk://#diff-85499a9f23aab8267292ad5379a9cade6bb56c614637a101b1aa71c47024b553R1-R94): Added a new `DesktopLeaderboard` component to display the leaderboard for desktop users.
* [`app/(main)/leaderboard/_components/mobile-leaderboard.tsx`](diffhunk://#diff-8fd6df27a9475264da9e3fbdd1f3aea5465e6e8e70468a962523b0bfd99f4620R1-R54): Added a new …
> [added] Mobile leaderboard page

- app/(marketing)/_components/heading.tsx
This pull request makes updates to the `app/(marketing)/_components/heading.tsx` file to refine the user interface and improve the clarity of the displayed messages. The most important changes include replacing icons and updating the accompanying text.
User Interface Improvements:
* Replaced the `Share` icon with the `Users` icon to better represent the action of comparing scores with friends. Updated the text to "Compare scores with friends" for clarity.
* Modified the text for the `CopyCheck` icon section to specify "Practice with AI images" instead of the more generic "Practice with Images and Text."
Dependency Updates:
* Updated the import statement to replace `Share` with `Users` from the `lucide-react` library.
> [fix] Update homepage text

- components/navbar/navbar.tsx
This pull request includes a small update to the `Navbar` component in `components/navbar/navbar.tsx`. The change refactors the `Flame` component's `className` logic to improve readability and correctness.
* [`components/navbar/navbar.tsx`](diffhunk://#diff-6401eaec6ba32926e78bdb4fb50d10a41c75c9efb2a09f294c1eb7fb2617b784L108-R115): Updated the `Flame` component to simplify the conditional logic in its `className` property, ensuring proper handling of the `fill-[#1C0F13]` class based on the user's streak and play timestamp.
> [fix] Streak of 0 showed filled in flame when it should be outlined

- components/Logo.tsx
Once we decide to do this, we can take the website out of beta, and I'll allow users to make accounts.
This pull request includes a minor update to the `Logo` component. The change replaces the logo image file from `Wordmark-beta.svg` to `Wordmark_Logo.svg` and adjusts the width back to `200` as the beta phase is complete.
> [removed] Remove beta from navbar

- app/(main)/about/page.tsx
This pull request updates the titles displayed on the About page to reflect more consistent and team-oriented naming conventions for team members.
Changes to team member titles:
* Updated `Dylan Ravel`'s title from "Development Lead" to "Software Team Lead." (`app/(main)/about/page.tsx`, [app/(main)/about/page.tsxL49-R72](diffhunk://#diff-b6968fe0e1479fb133cb135d3843fb79f1de33bcab3a2c16e01bc38e0ef1f4e8L49-R72))
* Updated `Divi Newton`'s title from "Design Lead" to "Design Team Lead." (`app/(main)/about/page.tsx`, [app/(main)/about/page.tsxL49-R72](diffhunk://#diff-b6968fe0e1479fb133cb135d3843fb79f1de33bcab3a2c16e01bc38e0ef1f4e8L49-R72))
* Updated `Noslen Cruz-Muniz`'s title from "Curriculum Lead" to "Curriculum Team Lead." (`app/(main)/about/page.tsx`, …
> [improved] Changed "Development Team" to "Software Team"

- app/(developer)/admin/_components/_quick-links/quick-links.tsx
- app/(developer)/admin/page.tsx
This pull request introduces a new `QuickLinks` component to the admin dashboard and reorganizes the layout by replacing a placeholder statistics section with this new component. The changes improve navigation by providing quick access to key external resources.
* Added a new `QuickLinks` component in `app/(developer)/admin/_components/_quick-links/quick-links.tsx`. This component displays buttons linking to the Convex Dashboard, Clerk Dashboard, and GitHub Repository.
* Imported the `QuickLinks` component into `app/(developer)/admin/page.tsx` and integrated it into the admin dashboard layout. [[1]](diffhunk://#diff-e844bfac49a2756c9ef0bc6c933ae168098e39e6bfa9a80bc222a7f4fc2288cbR4) [[2]](diffhunk://#diff-e844bfac49a2756c9ef0bc6c933ae168098e39e6bfa9a80bc222a7f4fc2288cbR14-L17)
* Replaced …
> [added] Quick Links section on admin dashboard
